import type { Container } from '../types';

// TODO: Replace with Portainer API call:
// GET https://<portainer-host>/api/endpoints/1/docker/containers/json?all=true
// Headers: { 'X-API-Key': '<your-portainer-api-token>' }
// Stats per container: GET /api/endpoints/1/docker/containers/{id}/stats?stream=false

export const MOCK_CONTAINERS: Container[] = [
  {
    id: 'a1b2c3d4e5f6a1b2',
    name: 'plex',
    image: 'plexinc/pms-docker',
    tag: 'latest',
    status: 'running',
    cpu: 4.2,
    memory: 1024,
    memoryLimit: 4096,
    uptime: '12 days ago',
    ports: [{ private: 32400, public: 32400, protocol: 'tcp' }],
  },
  {
    id: 'b2c3d4e5f6a1b2c3',
    name: 'jellyfin',
    image: 'jellyfin/jellyfin',
    tag: '10.9.7',
    status: 'running',
    cpu: 2.1,
    memory: 768,
    memoryLimit: 4096,
    uptime: '8 days ago',
    ports: [{ private: 8096, public: 8096, protocol: 'tcp' }],
  },
  {
    id: 'c3d4e5f6a1b2c3d4',
    name: 'pihole',
    image: 'pihole/pihole',
    tag: '2024.07.0',
    status: 'running',
    cpu: 0.3,
    memory: 128,
    memoryLimit: 512,
    uptime: '30 days ago',
    ports: [
      { private: 80, public: 8080, protocol: 'tcp' },
      { private: 53, public: 53, protocol: 'udp' },
    ],
  },
  {
    id: 'd4e5f6a1b2c3d4e5',
    name: 'portainer',
    image: 'portainer/portainer-ce',
    tag: '2.21.1',
    status: 'running',
    cpu: 0.5,
    memory: 64,
    memoryLimit: 256,
    uptime: '30 days ago',
    ports: [
      { private: 9000, public: 9000, protocol: 'tcp' },
      { private: 9443, public: 9443, protocol: 'tcp' },
    ],
  },
  {
    id: 'e5f6a1b2c3d4e5f6',
    name: 'overseerr',
    image: 'sctx/overseerr',
    tag: 'latest',
    status: 'running',
    cpu: 1.8,
    memory: 256,
    memoryLimit: 1024,
    uptime: '5 days ago',
    ports: [{ private: 5055, public: 5055, protocol: 'tcp' }],
  },
  {
    id: 'f6a1b2c3d4e5f6a1',
    name: 'grafana',
    image: 'grafana/grafana',
    tag: '11.1.0',
    status: 'running',
    cpu: 1.2,
    memory: 192,
    memoryLimit: 512,
    uptime: '15 days ago',
    ports: [{ private: 3000, public: 3000, protocol: 'tcp' }],
  },
  {
    id: 'a2b3c4d5e6f7a2b3',
    name: 'nginx-proxy-manager',
    image: 'jc21/nginx-proxy-manager',
    tag: '2.11.3',
    status: 'running',
    cpu: 0.4,
    memory: 96,
    memoryLimit: 256,
    uptime: '30 days ago',
    ports: [
      { private: 80, public: 80, protocol: 'tcp' },
      { private: 443, public: 443, protocol: 'tcp' },
      { private: 81, public: 81, protocol: 'tcp' },
    ],
  },
  {
    id: 'b3c4d5e6f7a2b3c4',
    name: 'nextcloud',
    image: 'nextcloud',
    tag: '29-apache',
    status: 'paused',
    cpu: 0,
    memory: 512,
    memoryLimit: 2048,
    uptime: '2 days ago',
    ports: [{ private: 80, public: 8888, protocol: 'tcp' }],
  },
  {
    id: 'c4d5e6f7a2b3c4d5',
    name: 'watchtower',
    image: 'containrrr/watchtower',
    tag: 'latest',
    status: 'running',
    cpu: 0.1,
    memory: 32,
    memoryLimit: 128,
    uptime: '30 days ago',
    ports: [],
  },
  {
    id: 'd5e6f7a2b3c4d5e6',
    name: 'home-assistant',
    image: 'ghcr.io/home-assistant/home-assistant',
    tag: '2024.7.3',
    status: 'exited',
    cpu: 0,
    memory: 0,
    memoryLimit: 2048,
    uptime: '3 hours ago',
    ports: [{ private: 8123, public: 8123, protocol: 'tcp' }],
  },
];
